development:
  host: localhost
  port: 3306
  username: username
  password: password
  database: database
  encoding: utf8
  adapter: mysql2
  local_infile: true
  reconnect: true

production_readonly:
  host: host
  port: 3306
  username: username
  password: password
  database: database
  encoding: utf8
  adapter: mysql2
  local_infile: true
  reconnect: true
  pool: 50
  socket: /path/to/mysqld.sock
